name: 'File Access'
description: 'Read or update file.'
inputs:
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
  repository:
    description: 'Owner and repository name. For example, "Codertocat/Hello-World".'
    default: ${{ github.repository }}
    required: true
  input:
    description: 'Input settings to read or write files, can be specific value or file path. (Possible representation types: "Json" or "Yaml".)'
    required: true
  output:
    description: 'Path to output result as file.'
    required: false
outputs:
  result:
    description: 'Action result.'
runs:
  using: 'node12'
  main: 'dist/index.js'
