name: 'File Access'
description: 'Read or update file.'
inputs:
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
  repository:
    description: 'Owner and repository name. For example, "Codertocat/Hello-World".'
    default: ${{ github.repository }}
    required: true
  input:
    description: 'Input settings to read or write files, can be specific value or file path. (Possible representation types: "Json" or "Yaml".)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'  
  color: 'gray-dark'
